version: '3.9'
services:
  gameserver:
    build:
      context: .
      dockerfile: './docker/gameserver/Dockerfile'
    ports:
      - '3000:3000'
  botproxy:
    build:
      context: .
      dockerfile: './docker/botproxy/Dockerfile'
    ports:
      - '3000:3000'
  shardmanager:
    build:
      context: .
      dockerfile: './docker/shardmanager/Dockerfile'
    ports:
      - '3000:3000'
