# To remove unused docker images run:
# docker rmi (docker images -f "dangling=true" -q) -f
version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: './docker/web/Dockerfile'
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - WEB_HOST_ID=0
      - WEB_HOST_NAME=mangoweb
      - WEB_SERVER_URL=localhost:5000
  gameserver:
    build:
      context: .
      dockerfile: './docker/gameserver/Dockerfile'
    ports:
      - '3000:3000'
    environment:
      - GAME_SERVER_HOST_PORT=3000
      - GAME_SERVER_HOST_ID=0
      - GAME_SERVER_HOST_NAME=mango
      - BOT_IPC_URL=localhost:2000
  shardmanager:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: './docker/shardmanager/Dockerfile'
    ports:
      - '3000:3000'
