---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: ingress-nginx
data:
  error-log-level: 'debug'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sharding
data:
  totalShards: '2'
  shardManagerCount: '2'
  shardManagerPodPrefix: 'shardmanager-'
  shardManagerPodAddress: 'http://shardmanager-%ID%.shardmanager.default.svc.cluster.local:3000'
  gameServerUrlInternal: 'http://gameserver:3000'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web
data:
  port: '5000'
  id: '0'
  name: mosog
  url: 'https://www.arcadecord.com'
  gameServerUrl: 'https://api.arcadecord.com'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gameserver
data:
  port: '3000'
  name: mosoggame
  id: '1'
  redis: 'redis://redis-server:6379'
---
